<?xml version="1.0" encoding="utf-8"?><Database Name="ReUsableDBWinform" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WINDOWS-PC\MSSQLSERVER2012;Initial Catalog=ReUsableDBWinform;Persist Security Info=True;User ID=sa" SettingsObjectName="iwork.autobits.inventory.Properties.Settings" SettingsPropertyName="ReUsableDBWinformConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RolePermission" Member="RolePermissions">
    <Type Name="RolePermission">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SystemFormID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role" Member="Role1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SystemForms" Member="SystemForms">
    <Type Name="SystemForm">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ctrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductHistory" Member="ProductHistories">
    <Type Name="ProductHistory">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QtyIn" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyOut" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyAdjustment" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyCurrent" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CurrentQuantity" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.AuthenticateUsers" Method="AuthenticateUsers">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="isSuccess" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <ElementType Name="AuthenticateUsersResult">
      <Column Name="UserID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UsersSelect" Method="UsersSelect">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="keyword" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="UsersSelectResult">
      <Column Name="UserID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UsersDelete" Method="UsersDelete">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UsersInsert" Method="UsersInsert">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UsersUpdate" Method="UsersUpdate">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProductInsert" Method="ProductInsert">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Cost" Parameter="cost" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProductStockADJUST" Method="ProductStockADJUST">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QtyAdjust" Parameter="qtyAdjust" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProductStockIn" Method="ProductStockIn">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QtyIn" Parameter="qtyIn" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProductStockOut" Method="ProductStockOut">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QtyOut" Parameter="qtyOut" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProductUpdate" Method="ProductUpdate">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Cost" Parameter="cost" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProductSelect" Method="ProductSelect">
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(500)" />
    <ElementType Name="ProductSelectResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CurrentQuantity" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ProductHistorySelect" Method="ProductHistorySelect">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="ProductHistorySelectResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QtyIn" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyOut" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyAdjustment" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyCurrent" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TransType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ProductHistorySelectRange" Method="ProductHistorySelectRange">
    <Parameter Name="ProductCode" Parameter="productCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="From" Parameter="from" Type="System.DateTime" DbType="Date" />
    <Parameter Name="To" Parameter="to" Type="System.DateTime" DbType="Date" />
    <ElementType Name="ProductHistorySelectRangeResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QtyIn" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyOut" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyAdjustment" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="QtyCurrent" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TransType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>